name: Expression Operators Demo

on:
  workflow_dispatch:
    inputs:
      env_name:
        description: 'Environment name'
        required: true
        default: 'staging'
      version:
        description: 'Version number'
        required: true
        default: '1.0.0'

env:
  RELEASE_STAGE: "beta"
  VERSION_MAJOR: "1"

jobs:
  operator-demo:
    runs-on: ubuntu-latest
    steps:
      # ( ) Logical grouping
      - name: Logical grouping example
        if: ${{ (github.ref == 'refs/heads/main') && (inputs.env_name == 'production') }}
        run: echo "🚀 Deploying production from main branch"

      # [ ] Index access
      - name: Index access example
        run: |
          echo "First character of ref: ${{ github.ref[0] }}"

      # . Property dereference
      - name: Property access example
        run: echo "Commit SHA: ${{ github.sha }}"

      # ! Not operator
      - name: Not operator example
        if: ${{ !(inputs.env_name == 'production') }}
