name: Repo Dispatch Example

on:
  repository_dispatch:
    types: [event1, event2]

jobs:
  dispatch-job:
    runs-on: ubuntu-latest
    steps:
      - name: Show Payload
        if: ${{ github.event_name == 'repository_dispatch' }}
        run: |
          echo "Payload: ${{ toJSON(github.event.client_payload) }}"

# Trigger via GitHub API (using curl)
# curl -X POST -H "Accept: application/vnd.github.v3+json" -H "Authorization: token YOUR_GITHUB_TOKEN" https://api.github.com/repos/{owner}/{repo}/dispatches -d '{"event_type":"event1","client_payload":{"passed":false,"message":"Error: timeout"}}'

# Trigger via GitHub client 
# gh api -X POST -H "Accept: application/vnd.github.v3+json" /repos/{owner}/{repo}/dispatches -f event_type=event1 -f client_payload[passed]=false -f client_payload[message]='Error: timeout'
