name: Use Secrets and Variables

on: push

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print secret and variable
        run: |
          echo "Variable value: ${{ vars.MY_VAR }}"
          echo "Secret value: ${{ secrets.MY_SECRET }}"
